version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    tty: true
    stdin_open: true

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_2022
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!