// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.NotificationDb
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20241222153603_Notification_Channel_Data")]
    partial class Notification_Channel_Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstructionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Notifications.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf7d73aa-c172-4eb2-9782-5491c76018b9"),
                            CreatedAt = new DateTime(2024, 12, 22, 15, 36, 1, 716, DateTimeKind.Utc).AddTicks(1024),
                            IsDeleted = false,
                            Name = "E-MAIL"
                        },
                        new
                        {
                            Id = new Guid("061898e6-c619-4f9e-96fc-f517e18f1fe7"),
                            CreatedAt = new DateTime(2024, 12, 22, 15, 36, 1, 716, DateTimeKind.Utc).AddTicks(1036),
                            IsDeleted = false,
                            Name = "SMS"
                        },
                        new
                        {
                            Id = new Guid("829fe06a-2fa2-477c-979d-d1080ca86bbc"),
                            CreatedAt = new DateTime(2024, 12, 22, 15, 36, 1, 716, DateTimeKind.Utc).AddTicks(1060),
                            IsDeleted = false,
                            Name = "PUSH"
                        });
                });

            modelBuilder.Entity("Domain.Notifications.NotificationChannelMapping", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("NotificationId", "ChannelId");

                    b.HasIndex("ChannelId");

                    b.ToTable("NotificationChannelMappings");
                });

            modelBuilder.Entity("Domain.Notifications.NotificationChannelMapping", b =>
                {
                    b.HasOne("Domain.Notifications.NotificationChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Notifications.Notification", "Notification")
                        .WithMany("ChannelMappings")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.Navigation("ChannelMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
