// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20241221124733_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed0c952e-9fb8-48f0-97f5-3c89d1fd9510"),
                            CreatedAt = new DateTime(2024, 12, 21, 12, 47, 31, 925, DateTimeKind.Utc).AddTicks(6636),
                            Email = "testuser1@example.com",
                            IsDeleted = false,
                            Name = "Test User 1"
                        },
                        new
                        {
                            Id = new Guid("e278b462-bb94-4719-acab-b4c2054ff18b"),
                            CreatedAt = new DateTime(2024, 12, 21, 12, 47, 31, 925, DateTimeKind.Utc).AddTicks(6641),
                            Email = "testuser2@example.com",
                            IsDeleted = false,
                            Name = "Test User 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
